<?php

final class Definitions {

    public const LEARNING_TYPE = [
        0 => 'CAT 1',
        1 => 'CAT 2',
        2 => 'CAT 3',
        3 => 'CAT 4',
        4 => 'CAT 5',
        5 => 'CAT 6',
        6 => 'CAT 7'
    ];

    public const FE_ORDER_BY = [
        0 => 'Rata più bassa',
        1 => 'Rata più alta',
        2 => 'Più recente',
        /*
        3 => 'Anticipo più basso',
        4 => 'Anticipo più alto',
        5 => 'Km annui più bassi',
        6 => 'Km annui più alti'
        */
    ];

    public const ORDER_BY = [
        0 => 'monthly_fee ASC',
        1 => 'monthly_fee DESC',
        2 => 'model_id DESC',
        3 => 'deposit ASC',
        4 => 'deposit DESC',
        5 => 'km_per_year ASC',
        6 => 'km_per_year DESC',
        7 => 'RAND()'
    ];

    public const BODY_TYPE = [
        'A'   => 'Aperta',
        'AT'  => 'Torpedo telonata',
        'B2V' => 'Berlina a due volumi',
        'B3V' => 'Berlina a tre volumi',
        'C2V' => 'Coupé a due volumi',
        'C3V' => 'Coupé a tre volumi',
        'M'   => 'Furgone',
        'MPW' => 'Multispazio',
        'P'   => 'Autotelaio cabinato',
        'PC'  => 'Pianale cabinato',
        'PS'  => 'Scudato',
        'S'   => 'Fuoristrada pick-up con hard top',
        'SH'  => 'Torpedo con hard top',
        'SW'  => 'Station wagon',
        'X'   => 'Non definita'
    ];

    public const NORMALIZED_BODY_TYPES = [
        'B2' => 'Berlina 2 volumi',
        'B3' => 'Berlina 3 volumi',
        'CP' => 'Coupè',
        'SV' => 'SUV',
        'MV' => 'Monovolume',
        'FS' => 'Fuoristrada',
        //'FR' => 'Furgone',
        'CB' => 'Cabrio',
        'SW' => 'Station wagon',
        //'PK' => 'Pickup',
    ];

    public const BODY_GROUPS = [
        'B2' => [
            'BE20',
            'BE22',
            'BE23',
            'BE25',
            'BE50'
        ],
        'B3' => [
            'BE30',
            'BE35'
        ],
        'PK' => [
            'BE70',
            'FU30',
            'FU31',
            'FU32',
            'FU36',
            'GI75',
            'BE80',
            'FU33',
            'FU34',
            'FU38',
            'FU39'
        ],
        'FS' => [
            'CAF0',
            'FU20',
            'FU22',
            'FU24',
            'FU26',
            'FU40',
            'FU42',
            'FU60'
        ],
        'CB' => [
            'CA09',
            'CA20',
            'CA25',
            'CA50',
            'CA55',
            'CO45'
        ],
        'CP' => [
            'CO10',
            'CO15'
        ],
        'SV' => [
            'FU50',
            'FU52',
            'FU54',
            'FU56'
        ],
        'SW' => [
            'GI20'
        ],
        'MV' => [
            'GI30',
            'GI40',
            'GI36',
            'GI43',
            'GI45'
        ],
        'FR' => [
            'GI50',
            'GI70',
            'GI72',
            'TE10',
            'TE20',
            'TE30',
            'GI32',
            'GI34',
            'GI60',
            'GI65',
            'TE15',
            'TE25',
            'TE40',
            'TE50',
            'TE60'
        ]
    ];

    public const FUEL_TYPE = [
        'D'	=> 'Gasolio',
        'B'	=> 'Benzina',
        'E'	=> 'Elettrica',
        'C'	=> 'Etanolo',
        'G'	=> 'GPL',
        'H'	=> 'Idrogeno',
        'W' => 'Ibrida',
        'M'	=> 'Metano',
        'X' => 'Non definita'
    ];

    public const GEAR_TYPE = [
        'A' => 'Automatico',
        'M' => 'Manuale',
        'V' => 'Variatore',
        'X' => 'Assente'
    ];

    public const EQUIPMENT_TYPE = [
        'S' => 'Di serie'
    ];

    public const CHANNEL_TYPE = [
        '1' => 'Google',
        '2' => 'Facebook'
    ];

    public const COUNTRIES = [
        "AF" => "Afghanistan",
        "AX" => "Aland Islands",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgio",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BQ" => "Bonaire",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brasile",
        "IO" => "British Indian Ocean Territory",
        "BN" => "Brunei Darussalam",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CY" => "Cipro",
        "VA" => "Città del Vaticano",
        "CC" => "Cocos (Keeling) Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "CI" => "Costa d'Avorio",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CW" => "Curacao",
        "DK" => "Danimarca",
        "KP" => "Democratic People's Republic of Korea",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "EC" => "Ecuador",
        "EG" => "Egitto",
        "SV" => "El Salvador",
        "AE" => "Emirati Arabi",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands (Malvinas)",
        "FO" => "Faroe Islands",
        "RU" => "Federazione Russa",
        "FJ" => "Fiji",
        "FI" => "Finlandia",
        "FR" => "Francia",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germania",
        "GH" => "Ghana",
        "JP" => "Giappone",
        "GI" => "Gibraltar",
        "GR" => "Grecia",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island and McDonald Islands",
        "HN" => "Honduras",
        "HK" => "Hong Kong",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran",
        "IQ" => "Iraq",
        "IE" => "Irlanda",
        "IM" => "Isole di Man",
        "IL" => "Israele",
        "IT" => "Italia",
        "JM" => "Jamaica",
        "JE" => "Jersey",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LS" => "Lesotho",
        "LV" => "Lettonia",
        "LB" => "Libano",
        "LR" => "Liberia",
        "LY" => "Libia",
        "LI" => "Liechtenstein",
        "LT" => "Lituania",
        "LU" => "Lussemburgo",
        "MO" => "Macao",
        "MK" => "Macedonia",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldive",
        "ML" => "Mali",
        "MT" => "Malta",
        "MA" => "Marocco",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "MX" => "Messico",
        "FM" => "Micronesia",
        "MD" => "Moldavia",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MZ" => "Mozambique",
        "MM" => "Myanmar",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norvegia",
        "OM" => "Oman",
        "NL" => "Paesi Bassi",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestina",
        "PA" => "Panama",
        "PG" => "Papua Nuova Guinea",
        "PY" => "Paraguay",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn",
        "PL" => "Polonia",
        "PT" => "Portogallo",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "GB" => "Regno Unito",
        "CZ" => "Repubblica Ceca",
        "DO" => "Repubblica Dominicana",
        "KR" => "Republic of Korea",
        "RO" => "Romania",
        "RW" => "Rwanda",
        "RE" => "Réunion",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "ST" => "Sao Tome and Principe",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SX" => "Sint Maarten (Dutch part)",
        "SK" => "Slovacchia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "SS" => "South Sudan",
        "ES" => "Spagna",
        "LK" => "Sri Lanka",
        "US" => "Stati uniti d'America",
        "ZA" => "Sud Africa",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SE" => "Svezia",
        "CH" => "Svizzera",
        "SZ" => "Swaziland",
        "SY" => "Syrian Arab Republic",
        "TW" => "Taiwan",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailand",
        "TL" => "Timor-Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turchia",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UA" => "Ucraina",
        "UG" => "Uganda",
        "HU" => "Ungheria",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VE" => "Venezuela",
        "VN" => "Viet Nam",
        "VG" => "Virgin Islands (UK)",
        "VI" => "Virgin Islands (USA)",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe"
    ];

    public const STATES = [
        "AG" => "Agrigento",
        "AL" => "Alessandria",
        "AN" => "Ancona",
        "AO" => "Aosta",
        "AR" => "Arezzo",
        "AP" => "Ascoli Piceno",
        "AT" => "Asti",
        "AV" => "Avellino",
        "BA" => "Bari",
        "BT" => "Barletta-Andria-Trani",
        "BL" => "Belluno",
        "BN" => "Benevento",
        "BG" => "Bergamo",
        "BI" => "Biella",
        "BO" => "Bologna",
        "BZ" => "Bolzano",
        "BS" => "Brescia",
        "BR" => "Brindisi",
        "CA" => "Cagliari",
        "CL" => "Caltanissetta",
        "CB" => "Campobasso",
        "CI" => "Carbonia-Iglesias",
        "CE" => "Caserta",
        "CT" => "Catania",
        "CZ" => "Catanzaro",
        "CH" => "Chieti",
        "CO" => "Como",
        "CS" => "Cosenza",
        "CR" => "Cremona",
        "KR" => "Crotone",
        "CN" => "Cuneo",
        "EN" => "Enna",
        "FM" => "Fermo",
        "FE" => "Ferrara",
        "FI" => "Firenze",
        "FG" => "Foggia",
        "FC" => "Forlì-Cesena",
        "FR" => "Frosinone",
        "GE" => "Genova",
        "GO" => "Gorizia",
        "GR" => "Grosseto",
        "IM" => "Imperia",
        "IS" => "Isernia",
        "AQ" => "L'Aquila",
        "SP" => "La Spezia",
        "LT" => "Latina",
        "LE" => "Lecce",
        "LC" => "Lecco",
        "LI" => "Livorno",
        "LO" => "Lodi",
        "LU" => "Lucca",
        "MC" => "Macerata",
        "MN" => "Mantova",
        "MS" => "Massa-Carrara",
        "MT" => "Matera",
        "VS" => "Medio Campidano",
        "ME" => "Messina",
        "MI" => "Milano",
        "MO" => "Modena",
        "MB" => "Monza e della Brianza",
        "NA" => "Napoli",
        "NO" => "Novara",
        "NU" => "Nuoro",
        "OG" => "Ogliastra",
        "OT" => "Olbia-Tempio",
        "OR" => "Oristano",
        "PD" => "Padova",
        "PA" => "Palermo",
        "PR" => "Parma",
        "PV" => "Pavia",
        "PG" => "Perugia",
        "PU" => "Pesaro e Urbino",
        "PE" => "Pescara",
        "PC" => "Piacenza",
        "PI" => "Pisa",
        "PT" => "Pistoia",
        "PN" => "Pordenone",
        "PZ" => "Potenza",
        "PO" => "Prato",
        "RG" => "Ragusa",
        "RA" => "Ravenna",
        "RC" => "Reggio Calabria",
        "RE" => "Reggio Emilia",
        "RI" => "Rieti",
        "RN" => "Rimini",
        "RM" => "Roma",
        "RO" => "Rovigo",
        "SA" => "Salerno",
        "SS" => "Sassari",
        "SV" => "Savona",
        "SI" => "Siena",
        "SR" => "Siracusa",
        "SO" => "Sondrio",
        "TA" => "Taranto",
        "TE" => "Teramo",
        "TR" => "Terni",
        "TO" => "Torino",
        "TP" => "Trapani",
        "TN" => "Trento",
        "TV" => "Treviso",
        "TS" => "Trieste",
        "UD" => "Udine",
        "VA" => "Varese",
        "VE" => "Venezia",
        "VB" => "Verbano-Cusio-Ossola",
        "VC" => "Vercelli",
        "VR" => "Verona",
        "VV" => "Vibo Valentia",
        "VI" => "Vicenza",
        "VT" => "Viterbo"
    ];

    public const RENT_DURATION_VALUES = [12, 18, 24, 36, 48, 72];
    public const OFFER_INSTALLMENT_VALUES = [250, 500, 750, 1000, 1250, 1500, 1750, 2000];
    public const OFFER_DEPOSIT_VALUES = [1000, 2000, 3000, 4000, 5000, 10000, 15000, 20000, 25000, 30000, 40000, 50000, 60000, 75000, 90000];

    public static function getValue($dictionary, $key): mixed {

        $constantProperty = sprintf('%s::%s', Definitions::class, $dictionary);

        if (!defined($constantProperty)) {
            return null;
        }
        
        $dictionary = constant($constantProperty);
        return $dictionary[$key] ?? null;
    }

}